In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[371, 3426, 2054, 2638],
 [371, 3426, 2054, 42],
 [371, 2176, 2054, 2303],
 [6922, 6599, 8419, 25, 6515],
 [6922, 6599, 8419, 25, 2279],
 [4217, 371, 2612, 2054, 4883],
 [6372, 5235, 3578, 25]]

In [5]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [6]:
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  371 3426 2054 2638]
 [   0    0    0    0  371 3426 2054   42]
 [   0    0    0    0  371 2176 2054 2303]
 [   0    0    0 6922 6599 8419   25 6515]
 [   0    0    0 6922 6599 8419   25 2279]
 [   0    0    0 4217  371 2612 2054 4883]
 [   0    0    0    0 6372 5235 3578   25]]


In [8]:
## feature representation
dim=10

In [9]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\PROJECTS\Simple-Rnn (IMDB)\myvenv\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step


array([[[-0.02937231,  0.04359505, -0.03174065, -0.02350891,
          0.03382076, -0.04703964,  0.00410317, -0.03856061,
         -0.03355497,  0.02596149],
        [-0.02937231,  0.04359505, -0.03174065, -0.02350891,
          0.03382076, -0.04703964,  0.00410317, -0.03856061,
         -0.03355497,  0.02596149],
        [-0.02937231,  0.04359505, -0.03174065, -0.02350891,
          0.03382076, -0.04703964,  0.00410317, -0.03856061,
         -0.03355497,  0.02596149],
        [-0.02937231,  0.04359505, -0.03174065, -0.02350891,
          0.03382076, -0.04703964,  0.00410317, -0.03856061,
         -0.03355497,  0.02596149],
        [-0.01620865, -0.02830802, -0.01258862,  0.01708538,
         -0.04604096, -0.00322694,  0.00600165, -0.04178758,
          0.01277746, -0.0226709 ],
        [ 0.03522165, -0.01408192,  0.01697353,  0.04213086,
         -0.00784278,  0.00935478,  0.01684341, -0.03643844,
         -0.0293828 , -0.00453486],
        [ 0.00372338, -0.03115822,  0.02588085, -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0,  371, 3426, 2054, 2638], dtype=int32)

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None